backend:
  name: git-gateway
  branch: master

media_folder: "src/static/img"
public_folder: "/static/img"

local_backend: true

collections:

  # NEW Events collection
  - label: "Events"
    name: "events"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Afbeeldingen"
        name: "images"
        widget: "list"
        allow_add: true
        min: 1
        field:
          label: "Afbeelding"
          name: "image"
          widget: "image"
      - { label: "Beschrijving", name: "body", widget: "markdown" }
